from storage.repos.companies import CompanyMixin
from storage.repos.taxonomy import TaxonomyMixin
from storage.repos.jobs import JobsMixin
from storage.repos.social import SocialMixin
from storage.repos.settings import SettingsMixin
from storage.repos.research import ResearchMixin
from storage.repos.canvas import CanvasMixin
from storage.repos.templates import TemplateMixin
from storage.repos.dimensions import DimensionsMixin
from storage.repos.discovery import DiscoveryMixin
from storage.repos.entities import EntityMixin
from storage.repos.extraction import ExtractionMixin
